variables:
	IMAGE_NAME: aadinnr/demo-docker-rp
	IMAGE_TAG: react-app-1.0

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:18
  before_script:
    - npm install --force
  script:
    - npm test
  only:
    - main

build:
  stage: build
  image: docker:28.0.1
  services:
    - docker:28.0.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
